# Platforms
#default.platform.name=CHROME
default.platform.name=android

# Android capabilities
android.platform.name=android
android.platform.version=14
android.device.name=emulator-5554
android.automation.name=UiAutomator2
android.app.path=/Users/abhishekjain/Downloads/latest.apk

# iOS capabilities
ios.platform.name=iOS
ios.platform.version=12.2
ios.device.name=iPhone X
ios.app.path=/Users/abhishekjain/Downloads/_Online.app
ios.no.reset=false

# Appium
appium.driver.implicit.timeout=10
appium.driver.url=http://127.0.0.1:4725/wd/hub

# Database
sqlite.db.url=database.sqlite

# UAT logout url
uat.url.logout=https://onlineuat..com/IB/api/CustomerLogin/logout
